export const User1 = {
  id:0,
  profilePicture:"iron.jpg",
  username:"Manas Manna",
}
export const Users = [
  {
    id:1,
    profilePicture: "1.webp",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "2.jpg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "2.png",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "3.png",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "4.png",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "5.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "5.png",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "6.jpg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "7.jpg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "8.png",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    name: "Safak Kocaoglu",
    desc: "Love For All, Hatred For None.",
    profilePicture: "New Folder/1.webp",
    photo: "1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    name: "Janell Shrum",
    profilePicture: "New Folder/2.jpg",
    photo: "2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    name: "Alex Durden",
    desc: "Every moment is a fresh beginning.",
    profilePicture: "New Folder/2.png",
    photo: "3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    name: "Alex Durden",
    profilePicture: "New Folder/3.png",
    photo: "4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    name: "Alex Durden",
    profilePicture: "New Folder/4.png",
    photo: "5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    name: "Alex Durden",
    profilePicture: "New Folder/5.jpg",
    photo: "6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    name: "Alex Durden",
    desc: "Never regret anything that made you smile.",
    profilePicture: "New Folder/5.png",
    photo: "7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    name: "Alex Durden",
    profilePicture: "New Folder/6.jpg",
    photo: "8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    name: "Alex Durden",
    desc: "Change the world by being yourself.",
    profilePicture: "New Folder/7.jpg",
    photo: "9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    name: "Alex Durden",
    profilePicture: "New Folder/8.png",
    photo: "10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
